POST http://localhost:3003/api/blogs/
Content-Type: application/json

{
  
  "author": "Tete",
  "title": "A mi me gusta el chatgpt",
  "url": "www.chatgpt.com",
  "likes": 1203,
  "user": "67fabf385b0c2dc8ce20e073"

  }
    
