POST http://localhost:3003/api/blogs/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZmFjYzI3ZTc5NGJiYjAyNmMxNGM2OCIsInVzZXJuYW1lIjoibWVyeXRvd2VycyIsImlhdCI6MTc0NDU1MTg3NH0.t30hNYTt0JtnI7O-QumindnBHF2dEeosnEW71FUdmrI

{
  
  "author": "Meri",
  "title": "Prueba Blog meri sin user",
  "url": "www.pruebaauth.com",
  "likes": 1203

  }
    
